//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akami_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Akami_ProjectEntities1 : DbContext
    {
        public Akami_ProjectEntities1()
            : base("name=Akami_ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsSet> ClientsSet { get; set; }
        public virtual DbSet<OrdersSet> OrdersSet { get; set; }
        public virtual DbSet<ProductsSet> ProductsSet { get; set; }
        public virtual DbSet<ProvidersSet> ProvidersSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
