//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akami_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdProduct { get; set; }
        public string Address_Delivery { get; set; }
        public string Delivery_method { get; set; }
        public string Payment_method { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual ProductsSet ProductsSet { get; set; }
    }
}
