//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akami_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductsSet()
        {
            this.OrdersSet = new HashSet<OrdersSet>();
        }
    
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Category_products { get; set; }
        public int IdProviders { get; set; }
        public long Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersSet> OrdersSet { get; set; }
        public virtual ProvidersSet ProvidersSet { get; set; }
    }
}
