//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akami_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProvidersSet()
        {
            this.ProductsSet = new HashSet<ProductsSet>();
        }
    
        public int Id { get; set; }
        public string Firm_Name { get; set; }
        public string Address_Firm { get; set; }
        public string Phone { get; set; }
        public string License_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsSet> ProductsSet { get; set; }
    }
}
